### ISSUE TITLE
一千五得到1005, 贰千伍输出0

### ISSUE THREAD

**Issue by youtrip** [yongzhuo/Tookit-Sihui#1]
```
    # 测试异常中文数字
    cn_num = ['两','十','一千五','一千零五','1000','贰千伍']
    for test_c in cn_num:
        print(ctn.compose_integer(test_c))
        print(ctn.str_to_number(test_c))
```

**Comment by yongzhuo** [comment]
暂时可能实现不了所有功能（只支持书面语等，大写汉字和口语模式未支持），你可以参考[https://github.com/Ailln/cn2an](https://github.com/Ailln/cn2an)项目，
该项目应该能大部分满足你的需求。
如issue: [https://github.com/Ailln/cn2an/issues/2](https://github.com/Ailln/cn2an/issues/2)

**Comment by yongzhuo** [comment]
已经修复
